FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

# Setează URL-ul de bază pentru build-ul React
ENV BASE_URL=/staging
RUN npm run build

# Doar copiază build-ul (nu pornește nginx)
FROM alpine AS output
WORKDIR /dist
COPY --from=builder /app/dist .
